#!/bin/sh

testcase_dir=$(dirname $0)
testcase_name="$1"

if [ x"$testcase_name" = "x" ]; then
    echo "Usage: $(basename $0) <testcase_name>"
    exit 1
fi

/root/.local/bin/tbot --lab $testcase_dir/lab_qemu.py --board $testcase_dir/board_qemu.py -T $testcase_dir "$testcase_name"
