#!/bin/sh

. $(dirname $0)/system.conf


app_name="$1"
all_apps="$(cd $project_linux_device_driver_dir/test_suite && make list) all list"

for app in $all_apps
do
    if [ x"$app" = x"$app_name" ]; then
        export ENV_CC_COMPILE=$cross_compile
        cd $project_linux_device_driver_dir/test_suite && make clean && make $app
        exit $?
    fi
done

echo "Usage: $(basename $0) <list | all | app_name>"
echo "    -- list     : list all applications name"
echo "    -- all      : compile all applications"
echo "    -- app_name : compile specified application"
exit 1
