#!/bin/sh

. $(dirname $0)/system.conf

if [ x"$1" = "x" -o x"$1" != "x-q" ]; then
    echo "==================================="
    echo "====  QEMU: Linux is starting  ===="
    echo "====  Press Ctrl+A+X to exit   ===="
    echo "==================================="
    echo ""
    
    sleep 1
fi

$qemu_system_arm -machine   vexpress-a9                                          \
                 -m         512M                                                 \
                 -kernel    $linux_kernel                                        \
                 -dtb       $linux_dtb                                           \
                 -drive     file=$linux_rootfs,if=sd,format=raw                  \
                 -net user,hostfwd=tcp::$ssh_guest_port-:22 -net nic             \
                 -append    "root=/dev/mmcblk0 rw console=ttyAMA0 init=/linuxrc" \
                 -nographic
