#!/bin/sh

. $(dirname $0)/system.conf

ssh_fwd="tcp::$ssh_guest_port-:22"
lepd_fwd="tcp::$project_linuxep_lepd_port-:12307"

other_options=""
if [ x"$1" = x"--debug" ]; then
    other_options="$other_options -gdb tcp::1234 -S"
fi

$qemu_system_arm -machine   vexpress-a9                                          \
                 -m         512M                                                 \
                 -kernel    $linux_kernel                                        \
                 -dtb       $linux_dtb                                           \
                 -drive     file=$linux_rootfs,if=sd,format=raw                  \
                 -net       user,hostfwd=$ssh_fwd,hostfwd=$lepd_fwd -net nic     \
                 -append    "root=/dev/mmcblk0 rw console=ttyAMA0 init=/linuxrc" \
                 -nographic $other_options
