#!/bin/sh

. $(dirname $0)/system.conf


$qemu_system_arm -machine   vexpress-a9                        \
                 -m         512M                               \
                 -kernel    $uboot_image                       \
                 -drive     file=$uboot_sd,if=sd,format=raw    \
                 -nographic
