#!/bin/sh

. $(dirname $0)/system.conf


command_str="/testcases/run_all_testcases"

mkdir -p $tbot_testcase_dir/log

docker run -it --rm                                       \
           -v $topdir:/linux_learning_environment         \
           -v $tbot_testcase_dir:/testcases               \
           -v $tbot_testcase_dir/log:/log                 \
           $tbot_docker_image                             \
           "$command_str"
