#!/bin/sh

. $(dirname $0)/system.conf


command_str="$1"

if [ x"$command_str" = "x" ]; then
    command_str="bash"
fi

mkdir -p $tbot_testcase_dir/log

docker run -it --rm                                       \
           -v $topdir:/linux_learning_environment         \
           -v $tbot_testcase_dir:/testcases               \
           -v $tbot_testcase_dir/log:/log                 \
           $tbot_docker_image                             \
           "$command_str"
